on:
  workflow_call:
    inputs:
      release-tag-name:
        required: true
        type: string
      push:
        required: true
        type: boolean
env:
  imageName: "tydiczj/pcidevices-controller"

jobs:
  dapper-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run dapper
        run: make ci

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ inputs.push == true }}
        with:
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_PASSWORD }}

      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: .
          platforms: linux/amd64,linux/arm64
          file: package/Dockerfile
          push: ${{ inputs.push }}
          #tags: ${{env.imageName}}:${{ inputs.release-tag-name }}
          tags: registry.cn-qingdao.aliyuncs.com/tydiczj/pcidevices-controller:latest